idf_component_register(
    SRCS
        "main.c"
        "sys_i2c.c"
        "sys_display.c"
        "sys_touch.c"
        "sys_battery.c"
        "sys_wifi.c"
        "sys_imu.c"
        "sys_button.c"
        "sys_config.c"
        "sys_sdcard.c"
        "app_framework.c"
        "ui_home.c"
        "ui_menu.c"
        "app_settings.c"
        "app_attitude.c"
    INCLUDE_DIRS ".")
